### ISSUE TITLE
Control over what version of `glibc` is used

### ISSUE THREAD

**Issue by jhwz** [goreleaser/goreleaser-cross#2]
I currently use this to cross compile to a few platforms, and it works great! One issue I'm having is the resulting binary is always built with a recent (ish) version of `glibc` and some of our servers are running an older version of glibc, meaning they can't be run in the native environment.

I understand this package is already doing a lot and this might be out of scope, I'm not entirely sure what needs to change but I'd imagine it has something to do with the Dockerfile using `bullseye` and not an older environment like `stretch`? It would be awesome if you were able to choose which environment to use!

**Comment by troian** [comment]
Hi @jhwz 
I think the `sysroot` is what you are looking for 😉 
the [example](https://github.com/goreleaser/goreleaser-cross-example) is using [custom sysroot](https://github.com/goreleaser/goreleaser-cross-example-sysroot) with all custom libs including glibc.

Let me know if you need any more help with this topic.

**Comment by jhwz** [comment]
I was coming to that conclusion! 

I tried it out and had a few issues with the compiler not being able to find `libgcc_so.1`:
```
# runtime/cgo
/usr/bin/ld: cannot find libgcc_s.so.1
collect2: error: ld returned 1 exit status
```

To extract the sysroot I used the script given, but looking at the custom sysroot repo you linked the sysroot has symlinks that I don't have so there's a chance I'm getting something wrong.. Will keep having a play when I have time!

**Comment by troian** [comment]
Yeah, symlinks are the hard part when they are absolute.
You may need to tinker with `PKG_CONFIG_PATH ` [check here](https://github.com/goreleaser/goreleaser-cross-example/blob/master/.goreleaser.yaml) and `CGO_C(XX)FLAGS`.

Should be pretty much it. We've done it on different sorts of projects

**Comment by jhwz** [comment]
Ahh I had briefly looked at that but didn't know what the `PKG_CONFIG_PATH` was (this is all out of my comfort zone). Cheers, I'll give that a crack

**Comment by troian** [comment]
See if the first answer from this [thread](https://askubuntu.com/questions/210210/pkg-config-path-environment-variable) improves visibility.

I'll close the ticket for now. Feel free to reopen if the issue needs a response from us.

**Comment by jhwz** [comment]
So interestingly, even after setting the sysroots and setting the `PKG_CONFIG_PATH` to all of the `pkgroot`s in my clone, the build won't run on the other machine:
```
./mybinary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./mybinary)
```
is that something to do with the version of gcc I'm compiling with?

**Comment by troian** [comment]
it still seems to link with host glibc. did you mount sysroot to the docker container? this is how it is done in [the example](https://github.com/goreleaser/goreleaser-cross-example/blob/46f268b02b402c9ada0002e55a4929f66e7e594a/Makefile#L23) I referenced above.
try to use linker flag `-Wl,-dynamic-linker,<libc path>`. with example above it will be something like this `-Wl,-dynamic-linker,/lib)/ld-linux.so.2`. but honestly, it is unnecessary with modern gcc

also, it is good to enable linker verbose mode to see where it is trying to find libc. `-Wl,--verbose` is for it.

**Comment by jhwz** [comment]
Sorry I should give you more context with the commands I'm running, the docker command looks like:
```sh
docker run --rm \
    --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v `pwd`:/build \
    -w /build \
    -v /home/joel/Desktop/hurricane-sysroot:/sysroots/linux_amd64 \
    goreleaser/goreleaser-cross --rm-dist --snapshot
```

and then in the `.goreleaser.yml` I have:
```yaml
  - main: ./cmd/mybinary
    id: linux_amd_build
    binary: mybinary
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CGO_FLAGS=--sysroot=/sysroots/linux_amd64
      - CGO_LDFLAGS=--sysroot=/sysroots/linux_amd64
      - PKG_CONFIG_SYSROOT_DIR="/sysroots/linux_amd64"
      - PKG_CONFIG_PATH="/sysroots/linux_amd64/usr/lib/x86_64-linux-gnu/pkgconfig:/sysroots/linux_amd64/usr/lib/pkgconfig"
    targets: [linux_amd64]
    tags: [release]
```

I think it is finding the `/sysroots`, when I put in the incorrect path for the `CGO_FLAGS` it complains that it cannot find the correct files, I'll try with the linker flags
