### ISSUE TITLE
Image no longer works in GitHub Actions

### ISSUE THREAD

**Issue by arbourd** [goreleaser/goreleaser-cross#29]
Due to a [bug in actions/checkout](https://github.com/actions/checkout/issues/1169), this action cannot be used as a container without an additional step:

```yaml
- run: git config --system --add safe.directory <path>
```

This is not unique to `goreleaser-cross` and will affect all versions until actions/checkout is fixed.

But, in the meantime, there is a method we can apply to the image that will allow it work without that extra step in the workflows. We could bake the command into the image itself with something like:

```dockerfile
RUN git config --system --add safe.directory '*'
```

This would effectively disable the safe directory functionality within the goreleaser-cross container.

**Comment by troian** [comment]
interesting, so [this](https://github.com/goreleaser/goreleaser-cross/blob/45adc846328f94b76feadc827361538af577a81f/entrypoint.sh#L33) does not work? needs to be a wildcard `*` ?

**Comment by arbourd** [comment]
Oh, I didn't know that was even in there! No, the `pwd` should be fine and it's a better/safer solution than what I suggested. The wildcard would match everything.

It might still be broken in actions because the global config doesn't seem to exist properly. Let me test with the latest `v1.20.0` -- I was using `1.19.4` earlier.

**Comment by troian** [comment]
try image from `ghcr.io`

**Comment by arbourd** [comment]
Appears to be unresolved:

`  ⨯ release failed after 0s                  error=current folder is not a git repository`

I build and try `--system` over `--global` and see if that resolves it tomorrow/Monday.

**Comment by troian** [comment]
i think the best option would be to keep an extra run step instead of adding it goreleaser-cross and wait till `checkout/action` makes a fix

**Comment by kamikazechaser** [comment]
For those who are facing the same issue, here is a fix:

```yaml
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Workaround Git Security Warning
        run: |
          # Workaround a bug in github actions:
          git config --global --add safe.directory "$GITHUB_WORKSPACE"          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
```
