### ISSUE TITLE
Producing a .dll.exe where I was expecting a .dll

### ISSUE THREAD

**Issue by wayneforrest** [goreleaser/goreleaser-cross#37]
Help needed please:

I have the following configuration, and when a do a build, the output binary has the `.exe.dll` extension.

Also when try to use the  `.exe.dll` renamed to`.dll` in Visual Studio, it's reported that it's not a valid `.dll` file. (_I presume the binary format for .exe and .dll is somewhat different_. If found this on StackOverflow:`IMAGE_NT_HEADERS. For a DLL, it has the IMAGE_FILE_DLL (0x2000) flag turned on. For a EXE it's the IMAGE_FILE_EXECUTABLE_IMAGE (0x2) flag.`

Here is my configuration that is producing a `.exe.dll`

I am setting the `flags` as follows: `-buildmode=c-shared`

```
builds:
  - id: windows-amd64
    main: ./
    binary: cal-lib.dll
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -buildmode=c-shared
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: windows-arm64
    main: ./
    binary: cal-lib.dll
    goos:
      - windows
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags:
      - -buildmode=c-shared
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: golang-cross
    builds:
      - windows-amd64
      - windows-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: goreleaser
    name: cal-lib.dll
  prerelease: auto
  draft: false
```
