### ISSUE TITLE
Docker platform discrepancies 

### ISSUE THREAD

**Issue by maoueh** [goreleaser/goreleaser-cross#43]
Today, if you run `docker run --platform linux/arm64 ...` and `docker run --platform linux/amd64 ...` the set of system include paths is not consistent on disk:

```
docker run --platform=linux/amd64 --rm -it --entrypoint bash goreleaser/goreleaser-cross:v1.20.5 -c "ls /usr | grep -E '(aarch64-linux-gnu|x86_64-linux-gnu)'"
aarch64-linux-gnu

docker run --platform=linux/arm64 --rm -it --entrypoint bash goreleaser/goreleaser-cross:v1.20.5 -c "ls /usr | grep -E '(aarch64-linux-gnu|x86_64-linux-gnu)'"
x86_64-linux-gnu
```

This means that if you run the `--platform=linux/arm64` version, path `/usr/aarch64-linux-gnu` does not exist as it's directly `/usr` and the opposite for `--platform=linux/amd64` (path `/usr/x86_64-linux-gnu` does not exist).

I think we can make image consistent across platform by having 3 symlinks to `/usr/{include,lib,bin}`. If you agree, I would like to propose a PR for this.

**Comment by troian** [comment]
thanks for reporting,
mind showing use-case when this is causing issues

**Comment by maoueh** [comment]
It's unclear to me yet if it's actually a real problem :) I was adding a new build for `linux/arm64` and for `linux/amd64` I had defined:

```
  - id: linux-amd64
    main: ./cmd/{{ .global.Binary }}
    binary: {{ .global.Binary }}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - C_INCLUDE_PATH=/usr/x86_64-linux-gnu/include
      - LIBRARY_PATH=/usr/x86_64-linux-gnu/lib
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{`{{.Version}}`}}
```

So I was looking for the exact include path replacement for `/usr/x86_64-linux-gnu/{include,lib}` which I expected should have been at `/usr/aarch64-linux-gnu`. But I'm running the `linux/arm64` version of the Docker image so the path I was looking for is actually `/usr/{include,lib}`.

I'm not 100% sure it's a real problem, I think maybe the `/usr/include` will be checked anyway so it's gonna work.

I'm trying to build this `linux/arm64` version as we speak, so I'll let you know.
