### ISSUE TITLE
release failed when running in a container 

### ISSUE THREAD

**Issue by dwisiswant0** [goreleaser/goreleaser-cross#50]
Hello, I intended to experiment with cross-compilation using goreleaser-cross within a container. However, I encountered an issue where `goreleaser` detected that the `cwd` is "**not a git repository**." I'm looking for any suggestions on why this might occur and if there's a possible workaround.

Below is the GitHub workflow snippet that only has two steps.

```yaml
# SNIPPED
jobs:
  release:
    name: goreleaser-cross
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (inputs.job == 'release' || inputs.job == 'both')) }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: "${{ inputs.tag }}"
          fetch-depth: 0

      - run: goreleaser release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: "${{ github.workspace }}"
```

Error occurred:

```shell
  goreleaser release
# shell: sh -e {0}
# env:
#   GITHUB_TOKEN: ***
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
    • using token from "$GITHUB_TOKEN"
  • getting and validating git state
  ⨯ release failed after 0s                  error=current folder is not a git repository
Error: Process completed with exit code 1.
```

Thanks!
