### ISSUE TITLE
Windows 386 support

### ISSUE THREAD

**Issue by shaikh-shahid** [goreleaser/goreleaser-cross#54]
Hi Guys, 
I am trying to build for windows and i see we don't support 386 arch. However, Goreleaser main module does support windows 386. I am confused and need some assistant on the same.

**Comment by alex-dna-tech** [comment]
It all depends on what operating system you want to run binary. The latest go version supporting Windows XP is `v1.10` but `goreleaser-cross` starts from [v1.17.6-rc0](https://github.com/goreleaser/goreleaser-cross/releases/tag/v1.17.6-rc0). 
So the earliest version you can try is Windows 7 (go v1.20 last support).
You can try this:
```yml
  - id: helloworld-windows-386
    binary: helloworld
    main: ./cmd/helloworld
    goarch:
      - 386
    goos:
      - windows
    env:
      - CC=/llvm-mingw/bin/i686-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/i686-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe
     ```
