### ISSUE TITLE
Windows AMD build is failing 

### ISSUE THREAD

**Issue by y-bruin** [goreleaser/goreleaser-cross#84]
Hi Guys, I am trying to build for windows and my build is failing for amd64 arch. 

My Goreleaser Config 
```
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: bruin-windows-amd64
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w32--gcc
      - CXX=x86_64-w32-mingw64-g++
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
    flags:
      - -v
      - -trimpath
      - -buildmode=exe 
```

It is throwing me error 
```
docker run -it --rm -e VERSION=0.0.1  -v $(pwd):/src -w /src goreleaser/goreleaser-cross:v1.22 release --snapshot --clean
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lRstrtmgr
collect2: error: ld returned 1 exit status
```

**Comment by y-bruin** [comment]
cc: @caarlos0

**Comment by troian** [comment]
@y-bruin it cannot locate the library.
check [this example](https://github.com/goreleaser/goreleaser-cross-example/blob/c45dc32486e1532f330702104e2fd527891b44b9/.goreleaser.yaml#L28..L33). it's for linux, so you'll need to figure out how to set it on windows

**Comment by y-bruin** [comment]
@troian  That's where i am struggling , Do you have any windows example ?

**Comment by troian** [comment]
I don't use Windows myself, but as you're using GCC, it should be all same across all platforms.
GCC has options `-L` which allows to specify it in `CGO_ LDFLAGS`.

Add following to the `env` section of the amd64 build
`CGO_ LDFLAGS=-L<absolute path to the library location>`

**Comment by y-bruin** [comment]
can you suggest changes in my config , I found that this image support windows amd64 but not working for me 

```
  - id: bruin-windows-amd64
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR=-I/usr/x86_64-w64-mingw32/lib
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
    flags:
      - -trimpath
      - -buildmode=exe
```
