### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by dwisiswant0** [goreleaser/goreleaser-cross#93]
Error:

```
Run goreleaser build --clean --snapshot
  goreleaser build --clean --snapshot
  shell: sh -e {0}
  • skipping validate...
  • cleaning distribution directory
  • loading environment variables
  • getting and validating git state
    • accepting to run without a git repository because this is a snapshot
    • git state                                      commit=none branch=none current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped or partially skipped              reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=v0.0.0-none
  • running before hooks
    • running                                        hook=go mod tidy
    • running                                        hook=go mod verify
    • took: 53s
  • ensuring distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=dist/darwin-arm64_darwin_arm64_v8.0/pdmcp
    • building                                       binary=dist/darwin-amd64_darwin_amd64_v1/pdmcp
    • building                                       binary=dist/linux-amd64_linux_amd64_v1/pdmcp
    • building                                       binary=dist/linux-arm64_linux_arm64_v8.0/pdmcp
    • building                                       binary=dist/linux-386_linux_386_sse[2](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:2)/pdmcp
    • building                                       binary=dist/windows-amd64_windows_amd64_v1/pdmcp.exe
    • building                                       binary=dist/windows-arm64_windows_arm64_v8.0/pdmcp.exe
    • building                                       binary=dist/windows-[3](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:3)86_windows_386_sse2/pdmcp.exe
    • took: 26m[4](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:5)7s
  ⨯ build failed after 27m39s               
    error=
    │ build failed: exit status 1: # github.com/go-git/go-git/v[5](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:6)/plumbing/protocol/packp
    │ compile: writing output: write $WORK/b2328/_pkg_.a: no space left on device
    │ github.com/go-git/go-git/v5/plumbing/revlist: mkdir /tmp/go-build2895212128/b2334/: no space left on device
    │ github.com/go-git/go-git/v5/plumbing/format/objfile: mkdir /tmp/go-build2895212128/b2341/: no space left on device
    │ golang.org/x/sys/execabs: mkdir /tmp/go-build2895212128/b2343/: no space left on device
    │ github.com/kevinburke/ssh_config: mkdir /tmp/go-build2895212128/b2347/: no space left on device
    │ golang.org/x/crypto/ssh/knownhosts: mkdir /tmp/go-build2895212128/b2349/: no space left on device
    │ github.com/xanzy/ssh-agent: mkdir /tmp/go-build2895212128/b2350/: no space left on device
    │ github.com/go-git/go-git/v5/utils/merkletrie/filesystem: mkdir /tmp/go-build2895212128/b2351/: no space left on device
    │ github.com/go-git/go-git/v5/utils/merkletrie/index: mkdir /tmp/go-build2895212128/b2352/: no space left on device
    │ github.com/julienschmidt/httprouter: mkdir /tmp/go-build2895212128/b235[6](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:7)/: no space left on device
    │ github.com/felixge/fgprof: mkdir /tmp/go-build2[8](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:9)95212128/b2358/: no space left on device
    │ github.com/hako/durafmt: mkdir /tmp/go-build28[9](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:10)5212128/b2360/: no space left on device
    │ github.com/corpix/uarand: mkdir /tmp/go-build2895212128/b2363/: no space left on device
    │ github.com/tomnomnom/linkheader: mkdir /tmp/go-build2895212128/b2386/: no space left on device
    │ github.com/projectdiscovery/subfinder/v2/pkg/resolve: mkdir /tmp/go-build2895212128/b2406/: no space left on device
    │ github.com/projectdiscovery/urlfinder/pkg/extractor: mkdir /tmp/go-build2895212128/b2409/: no space left on device
    │ github.com/projectdiscovery/urlfinder/pkg/utils: mkdir /tmp/go-build2895212128/b2414/: no space left on device
    │ # github.com/mattn/go-sqlite3
    │ fatal error: error in backend: IO failure on output stream: No space left on device
    │ PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
    │ Stack dump:
    │ 0.	Program arguments: clang -target arm64-apple-darwin21.1 -mlinker-version=609 -isystem /usr/lib/llvm-[11](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:12)/bin/../lib/clang/11.0.1/include -isysroot /usr/local/osxcross/bin/../SDK/MacOSX[12](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:13).0.sdk -cxx-isystem /usr/local/osxcross/bin/../SDK/MacOSX12.0.sdk/usr/include/c++/v1 -mmacosx-version-min=11.0.0 -arch arm64 -Wno-liblto -I /github/home/go/pkg/mod/github.com/mattn/go-sqlite3@v1.[14](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:15).22 -fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2895212128/b1893=/tmp/go-build -gno-record-gcc-switches -fno-common -I $WORK/b1893/ -O2 -g -std=gnu99 -DSQLITE_ENABLE_RTREE -DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_TRACE_SIZE_LIMIT=[15](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:16) -DSQLITE_OMIT_DEPRECATED -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -Wno-deprecated-declarations -I/github/home/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.[22](https://github.com/projectdiscovery/mcp/actions/runs/14567511494/job/40859394274#step:6:23) -ffile-prefix-map=/github/home/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.22=
    │ 1.	<eof> parser at end of file
    │ go: failed to trim cache: write /github/home/.cache/go-build/trim.txt: no space left on device
    target=darwin_arm64_v8.0
```

GoReleaser config:

```yaml
version: 2

env:
  - CGO_ENABLED=1
  - APP_NAME=pdmcp
  - APP_COMMON_PKG=github.com/projectdiscovery/mcp/common

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: "darwin-amd64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "darwin-arm64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "darwin-386"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - "386"
    goos:
      - darwin
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "linux-amd64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "linux-arm64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "linux-386"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - "386"
    goos:
      - linux
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "windows-amd64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildvcs=false
      - -buildmode=exe
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "windows-arm64"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - arm64
    goos:
      - windows
    env:
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildvcs=false
      - -buildmode=exe
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

  - id: "windows-386"
    binary: "{{ .Env.APP_NAME }}"
    main: ./cmd/{{ .Env.APP_NAME }}
    goarch:
      - "386"
    goos:
      - windows
    flags:
      - -trimpath
      - -buildvcs=false
      - -buildmode=exe
    ldflags:
      - -s -w
      - -X {{ .Env.APP_COMMON_PKG }}.AppVersion={{ .Tag }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildTime={{ .Date }}
      - -X {{ .Env.APP_COMMON_PKG }}.BuildRev={{ .FullCommit }}
    hooks:
      post:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*

archives:
  - ids:
      - "darwin-amd64"
      - "darwin-arm64"
      - "darwin-386"
      - "linux-amd64"
      - "linux-arm64"
      - "linux-386"
      - "windows-amd64"
      - "windows-arm64"
      - "windows-386"
    name_template: >-
      {{- .Env.APP_NAME }}_{{- .Tag }}-
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: [binary]

sboms:
  - artifacts: binary
    documents:
      - >-
        {{- .Env.APP_NAME }}_{{ .Tag }}-
        {{- else }}{{ .Os }}{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: "{{ .Env.APP_NAME }}_{{ .Tag }}-checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^build"
      - "^chore"
      - "^ci"
      - "^docs"
      - "^refactor"
      - "^test"
      - Merge pull request
      - Merge branch

release:
  # draft: true
  prerelease: auto
  footer: |
    ## Verify

    > [!IMPORTANT]
    > It is strongly recommended to verify the integrity and security of the release assets before executing them. This helps mitigate potential risks associated with running unverified files.

    Verify the file using checksums.

    ```bash
    sha256sum --check --ignore-missing {{ .Env.APP_NAME }}_{{ .Tag }}-checksums.txt
    ```
  name_template: "{{ .Tag }}"
```

GitHub Workflow:

```yaml
# ... SNIPPED ...

  release:
    name: "Release test"
    needs: ["tests"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:latest
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: projectdiscovery/actions/setup/go@v1
      - run: apt-get update && apt install -y libpcap-dev # for naabu (go mod why github.com/gopacket/gopacket/pcap)
      - run: goreleaser build --clean --snapshot
```
```
